config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'ideas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ideas, only: [:index, :new, :create, :destroy, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :info, presence: true
  validates :price, presence: true

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments

  def self.search(search)
    return Idea.all() unless search
    Idea.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  def index
    require 'net/http'
    require 'json'

    @url = 'http://weather.livedoor.com/forecast/webservice/json/v1?city=270000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    @city_telop = @output['forecasts'][0]['telop']

    @ideas = Idea.all
    @all_ranks = Idea.find(Like.group(:idea_id).order('count(idea_id) desc').limit(10).pluck(:idea_id))
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.create(idea_params)
    redirect_to ideas_path
  end

  def destroy
    idea = Idea.find(params[:id])
    idea.destroy
  end

  def show
    @idea = Idea.find(params[:id])
    @like = Like.new
    @comment = Comment.new
    @comments = @idea.comments.includes(:user)
  end

  def search
    @ideas = Idea.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private  
  def idea_params
    params.require(:idea).permit(:title, :info, :price).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_header.html.haml
.header
  .header__info
    .header--logo
      %a(href="/")
        Idea-Maker
    .header--user
      -if user_signed_in?
        .header--user_name
          User Name:
          =current_user.name
  .header--weather
    =@city_telop
  .header--btn
    -if user_signed_in?
      .header--btn--logout
        = link_to " Logout", destroy_user_session_path ,class:"btn logout", method: :delete
      .header--btn--create
        = link_to "Post", new_idea_path , class: "btn create"
      %a(href="/users" class="header--btn--users btn")
        =icon("fas", "users")
      %a(href="/users/edit" class="header--btn--icon btn")
        =icon("fas", "cog")
    -else
      .header--btn--login
        = link_to "ログイン", new_user_session_path, class:"btn login"
      .header--btn--new
        = link_to "新規登録" , new_user_registration_path, class:"btn registration"
      %a(href="/users" class="header--btn--users btn")
        =icon("fas", "users")

app/views/ideas/_main_idea.html.haml
.html
  = render "header"
  .header-search
    =form_with(url: search_ideas_path, local: true, method: :get, class:"search-form") do |f|
      =f.text_field :keyword, placeholder: "Search", class: "search-input"
      -# =f.submit "Search", class: "search-btn"
  .body-logo
    ALL OF IDEAS
  .body
    -# ideaのブロックでひとかたまりのアイデア
    .ideas
      -@ideas.reverse_each do |idea|
        -if user_signed_in? 
          %a(href="/ideas/#{idea.id}" class="idea")
            .idea--title
              = idea.title
              -# idea-infoでユーザ名と値段の情報を持つ
            .idea--info 
              .idea--info--user_name
                = idea.user.name
              .idea--info--price
                price: $
                = idea.price
        -else
          .idea--title
            = idea.title
            -# idea-infoでユーザ名と値段の情報を持つ
          .idea--info 
            .idea--info--user_name
              = idea.user.name
            .idea--info--price
              price: $
              = idea.price
      %end
  
    .body-ranking
      -@all_ranks.each do |idea|
        = idea.title

    .google-maps
      会社位置
      #map
      %script{type:"text/javascript",src:"code1_1.js"}
      %script{src:"https://maps.googleapis.com/maps/api/js?key=AIzaSyDucSCzl_8X4EUv7XDnNBnsM2sAiUtWUG4&language=ja&callback=initMap"}

app/views/ideas/index.html.haml
.wrapper
  = render "main_idea"

app/views/ideas/new.html.haml
.content
  =render "header"
  .form
    %h2.form--logo
      Let's Show Your Idea!!
    =form_for @idea do |f|
      =f.text_field :title, class:"form--title form-color", placeholder:"Title"
      .form--box
      =f.text_area :info, class:"form--info form-color", placeholder:"Tell Me Your Special Idea!"
      =f.number_field :price, class:"form--price form-color", min:1, placeholder:"Input Your Idea's Worth($)"
      =f.submit "Send", class:"form--btn"

app/views/ideas/search.haml.haml
.wrapper
  .html
  = render "header"
  .header-search
    =form_with(url: search_ideas_path, local: true, method: :get, class:"search-form") do |f|
      =f.text_field :keyword, placeholder: "Search", class: "search-input"
      =f.submit "Search", class:"search-btn"
      -# =f.submit "Search", class: "search-btn"
  .body-logo
    ALL OF IDEAS
  .body
    -# ideaのブロックでひとかたまりのアイデア
    .ideas
      -@ideas.each do |idea|
        -if user_signed_in? 
          %a(href="/ideas/#{idea.id}" class="idea")
            .idea--title
              = idea.title
              -# idea-infoでユーザ名と値段の情報を持つ
            .idea--info 
              .idea--info--user_name
                = idea.user.name
              .idea--info--price
                price: $
                = idea.price
        -else
          .idea--title
            = idea.title
            -# idea-infoでユーザ名と値段の情報を持つ
          .idea--info 
            .idea--info--user_name
              = idea.user.name
            .idea--info--price
              price: $
              = idea.price
      %end

app/views/ideas/show.html.haml
.idea-wrapper
  =render "header"
  .idea-wrapper__logo
    IDEA INFORMATION
  .idea-wrapper__info
    .idea-wrapper__info--title
      title: 
      = @idea.title
    .idea-wrapper__info--name
      name: 
      = @idea.user.name
    .idea-like#like-link{ id: @idea.id }
      Like: 
      %h3
        =@idea.likes.count
      =render 'likes/like', collection: @ideas, as: :idea
  .idea-wrapper__box
    .idea-wrapper__box__content
      =@idea.info
  .idea-container
    %h2 Comments
  .comment-form
    =form_with model: [@idea, @comment], remote: true do |form|
      .idea-container-form
        =form.text_area :text, placeholder: "exchange your ideas!!", rows: "2"
        =form.submit "SEND", class:"comment-form-btn"
    .comments
      = render partial: "comments/comment"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaMaker3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>